# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('admin_user_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('street_number', models.IntegerField()),
                ('street_name', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DietType',
            fields=[
                ('diet_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('diet_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('cal', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('average_rating', models.FloatField(null=True)),
                ('fat', models.IntegerField()),
                ('fat_content', models.IntegerField()),
                ('fat_percent', models.IntegerField()),
                ('sat_fat', models.IntegerField()),
                ('sat_fat_content', models.IntegerField()),
                ('sat_fat_percent', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('carbs_content', models.IntegerField()),
                ('carbs_percent', models.IntegerField()),
                ('sodium', models.IntegerField()),
                ('sodium_content', models.IntegerField()),
                ('sodium_percent', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('protein_content', models.IntegerField()),
                ('protein_percent', models.IntegerField()),
                ('diet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.DietType')),
            ],
        ),
        migrations.CreateModel(
            name='FoodItemToLocation',
            fields=[
                ('food_item_to_location_id', models.AutoField(primary_key=True, serialize=False)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.Building')),
            ],
        ),
        migrations.CreateModel(
            name='LocationHours',
            fields=[
                ('location_hours_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(max_length=10)),
                ('opening_hour', models.TimeField()),
                ('closing_hour', models.TimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='MenuCalendar',
            fields=[
                ('menu_calendar_id', models.AutoField(primary_key=True, serialize=False)),
                ('data_available', models.DateField()),
                ('food_item_to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.FoodItemToLocation')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('star_rating', models.FloatField()),
                ('text', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.MenuCalendar')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.Login')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.User'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.User'),
        ),
        migrations.AddField(
            model_name='fooditemtolocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.Location'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.Location'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.User'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.Location'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.User'),
        ),
    ]
