# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_open_now',
            field=models.BooleanField(default=False),
        ),
    ]
