# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationhours',
            name='closing_hour',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='locationhours',
            name='opening_hour',
            field=models.TimeField(null=True),
        ),
    ]
