# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_location_is_open_now'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToLocation',
            fields=[
                ('user_to_location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.User')),
            ],
        ),
    ]
