# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_auto_20180323_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='weight',
            field=models.CharField(max_length=40),
        ),
    ]
