# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0004_auto_20180323_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='carbs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbs_content',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbs_percent',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat_content',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat_percent',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='product_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein_content',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein_percent',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='sat_fat',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='sat_fat_content',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='sat_fat_percent',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='sodium',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='sodium_content',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='sodium_percent',
            field=models.IntegerField(null=True),
        ),
    ]
