# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0005_auto_20180323_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='cal',
            field=models.IntegerField(null=True),
        ),
    ]
