# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-24 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0006_auto_20180323_0546'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteLocation',
            fields=[
                ('favorite_location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.Location')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.Student')),
            ],
        ),
        migrations.RemoveField(
            model_name='food',
            name='carbs_content',
        ),
        migrations.RemoveField(
            model_name='food',
            name='fat_content',
        ),
        migrations.RemoveField(
            model_name='food',
            name='protein_content',
        ),
        migrations.RemoveField(
            model_name='food',
            name='sat_fat_content',
        ),
        migrations.RemoveField(
            model_name='food',
            name='sodium_content',
        ),
    ]
