# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-24 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0007_auto_20180324_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='food',
            name='weight',
            field=models.CharField(max_length=2500),
        ),
    ]
