# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0008_auto_20180324_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menucalendar',
            old_name='data_available',
            new_name='date_available',
        ),
    ]
