# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0009_auto_20180326_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kitchen.Building'),
        ),
    ]
