# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0009_merge_20180325_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertolocation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='usertolocation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='location',
            name='is_open_now',
        ),
        migrations.DeleteModel(
            name='UserToLocation',
        ),
    ]
