# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0009_auto_20180326_0638'),
        ('kitchen', '0010_auto_20180325_2241'),
    ]

    operations = [
    ]
