# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0010_auto_20180326_1515'),
        ('kitchen', '0011_merge_20180326_1519'),
    ]

    operations = [
    ]
