# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0012_merge_20180326_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucalendar',
            name='date_available',
            field=models.CharField(max_length=25),
        ),
    ]
